- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/main.conf"
  queue.type: memory
  pipeline.workers: 2

- pipeline.id: second_pipeline
  path.config: "/usr/share/logstash/pipeline/second_pipeline.conf"
  queue.type: persisted
  pipeline.batch.size: 125
  queue.page_capacity: 50mb